# Devasy Patel
# 20BCE057
# Practicla 2b

OR, XOR, AND using ANN

In [1]:
# OR using ANN
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

X = [[0,0],[0,1],[1,0],[1,1]]
Y = [[0],[1],[1],[1]]
 
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(2, input_dim=2, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=1000, verbose=0)


In [3]:
# output using argmax
print(model.predict(X).round())
 

1/1 [==============================] - 0s 57ms/step
[[0.]
 [1.]
 [1.]
 [1.]]


AND using ANN
 

In [13]:
X = [[0,0],[0,1],[1,0],[1,1]]
Y = [[0],[0],[0],[1]]
model1 = tf.keras.models.Sequential()
model1.add(tf.keras.layers.Dense(2, input_dim=2, activation='relu'))
model1.add(tf.keras.layers.Dense(2, activation='relu'))
model1.add(tf.keras.layers.Dense(1, activation='sigmoid'))
model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model1.fit(X, Y, epochs=500, verbose=0)
print(model1.predict(X).round())

1/1 [==============================] - 0s 104ms/step
[[0.]
 [0.]
 [0.]
 [1.]]


XOR using ANN

In [9]:
Y = [[0],[1],[1],[0]]
model2 = tf.keras.models.Sequential()
model2.add(tf.keras.layers.Dense(2, input_dim=2, activation='relu'))
model2.add(tf.keras.layers.Dense(4, activation='relu'))
model2.add(tf.keras.layers.Dense(1, activation='sigmoid'))
model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model2.fit(X, Y, epochs=500, verbose=0)
print(model2.predict(X).round())

1/1 [==============================] - 0s 92ms/step
[[0.]
 [1.]
 [1.]
 [0.]]
