# Practical 5
1. Implementation of hidden markov models
2. Compute till steady state
3. Compute probability of a given state sequence

In [1]:
# task 1
# implement markov model
import numpy as np
state = np.array([0,1,2,3])
# state transition matrix
A = np.array([[0.5,0.2,0.2,0.1],
              [0.3,0.5,0.1,0.1],
              [0.2,0.3,0.3,0.2],
              [0.3,0.1,0.3,0.3]])

pie0 = np.array([0.25,0.25,0.25,0.25])

def calcu_pie(pie0, A, n):
    pie = pie0
    for i in range(n):
        pie = pie.dot(A)
    return pie

pie1 = calcu_pie(pie0, A, 1)

pie1

array([0.325, 0.275, 0.225, 0.175])

# task 2

In [8]:
# calculate till convergence or steady state
def calcu_pie_steady(pie0, A, n):
    pie = pie0
    for i in range(n):
        # print(i)
        pie = pie.dot(A)
        if np.allclose(pie, pie0):
            break
        pie0 = pie
    return pie

pie0 = np.array([0,1,0])
A = [[0.5, 0.1, 0.4],[0.1, 0.7, 0.2],[0.3, 0.3, 0.4]]
A = np.array(A)
pie2 = calcu_pie_steady(pie0, A, 100)
 
pie2

array([0.27272572, 0.40909343, 0.31818086])

In [14]:
# compute probablity of given state sequence
state_seq = [0, 2, 3, 1, 1]
def get_prob(state_seq, A):
    if(len(state_seq) == 1):
        return 1
    else:
        prob = 1
        for i in range(len(state_seq)-1):
            prob = prob * A[state_seq[i], state_seq[i+1]]
        return prob

get_prob(state_seq, A)

0.0020000000000000005

# Viterbi algorithm

In [7]:
# implement viterbi algorithm
# state transition matrix
# A = np.array([[0.5,0.2,0.2,0.1],
#                 [0.3,0.5,0.1,0.1],
#                 [0.2,0.3,0.3,0.2],
#                 [0.3,0.1,0.3,0.3]])
# # observation matrix
# B = np.array([[0.5,0.5],
#                 [0.4,0.6],
#                 [0.7,0.3],
#                 [0.2,0.8]])
# # initial state distribution
# pie0 = np.array([0.25,0.25,0.25,0.25])
# # observation sequence
# obs_seq = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
 
def viterbi(obs_seq, A, B, pie0):
    T = len(obs_seq)
    N = len(A)
    delta = np.zeros((N, T))
    phi = np.zeros((N, T))
    delta[:,0] = pie0 * B[:, obs_seq[0]]
    for t in range(1, T):
        for j in range(N):
            delta[j, t] = np.max(delta[:, t-1] * A[:, j]) * B[j, obs_seq[t]]
            phi[j, t] = np.argmax(delta[:, t-1] * A[:, j])
    q = np.zeros(T)
    q[T-1] = np.argmax(delta[:, T-1])
    for t in range(T-2, -1, -1):
        q[t] = phi[int(q[t+1]), t+1]
    return q

viterbi(obs_seq, A, B, pi)


array([0., 0., 0., 0.])

# Forward Algorithm

In [5]:
import numpy as np
# implement forward algorithm for HMM
# state transition matrix
pi = np.array([0.6, 0.4])
A = [[0.8, 0.2], [0.4, 0.6]]
B = [[0.4, 0.1, 0.2, 0.3], [0.3, 0.45, 0.2, 0.05]]
A = np.array(A)
B = np.array(B)
states = ['Paint', 'Clean', 'Shop', 'Bike']
obs_seq=[0, 1, 2, 3]
# calculate for aplha 1

def forward(obs_seq, A, B, pi):
    T = len(obs_seq)
    N = len(A)
    alpha = np.zeros((N, T))
    alpha[:,0] = pi * B[:, obs_seq[0]]
    for t in range(1, T):
        for j in range(N):
            alpha[j, t] = np.sum(alpha[:, t-1] * A[:, j]) * B[j, obs_seq[t]]
    return alpha

alpha = forward(obs_seq, A, B, pi)
alpha

array([[0.24     , 0.024    , 0.00816  , 0.0028512],
       [0.12     , 0.054    , 0.00744  , 0.0003048]])