In [1]:
from tensorflow import keras
import numpy
from numpy import array
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import SimpleRNN
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences

data = """ Jack and Jill went up the hill .\n To fetch a pail of water .\n Jack fell down and broke his crown .\n And Jill came tumbling after ."""
print("Data:", data, type(data))

data_splitted=data.split('\n') #returns a list of strings
print("Data_Splitted:", data_splitted, type(data_splitted))

ImportError: cannot import name 'pad_sequences' from 'keras.preprocessing.sequence' (c:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\preprocessing\sequence.py)

In [25]:
tokenizer=Tokenizer(filters='!"#$%&()*+,-/:;<=>?@[\]^_`{|}~')

tokenizer.fit_on_texts(data_splitted) #learns a vocabulary
print("Word Indices:", tokenizer.word_index) #tokenizer.word_index is a dictionary

vocab_size = len(tokenizer.word_index) + 1
print("Vocab Size:", vocab_size)

sequences=tokenizer.texts_to_sequences(data_splitted) #list of list
l=len(sequences)
print("Sequences:",sequences, type(sequences), l)

Word Indices: {'.': 1, 'and': 2, 'jack': 3, 'jill': 4, 'went': 5, 'up': 6, 'the': 7, 'hill': 8, 'to': 9, 'fetch': 10, 'a': 11, 'pail': 12, 'of': 13, 'water': 14, 'fell': 15, 'down': 16, 'broke': 17, 'his': 18, 'crown': 19, 'came': 20, 'tumbling': 21, 'after': 22}
Vocab Size: 23
Sequences: [[3, 2, 4, 5, 6, 7, 8, 1], [9, 10, 11, 12, 13, 14, 1], [3, 15, 16, 2, 17, 18, 19, 1], [2, 4, 20, 21, 22, 1]] <class 'list'> 4


In [27]:
X=list()
y=list()

for i in range(len(sequences)):
  X.insert(i,sequences[i][:-1])
  y.insert(i,sequences[i])

print("X=", X, "y=",y, type(X), type(y))

X= [[3, 2, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14], [3, 15, 16, 2, 17, 18, 19], [2, 4, 20, 21, 22]] y= [[3, 2, 4, 5, 6, 7, 8, 1], [9, 10, 11, 12, 13, 14, 1], [3, 15, 16, 2, 17, 18, 19, 1], [2, 4, 20, 21, 22, 1]] <class 'list'> <class 'list'>


In [33]:
maxlen = max([len(sequence) for sequence in X])
print("Maxlen:",maxlen)

#X=array(X)
#y=array(y)
#X=numpy.reshape(X,newshape=(l,-1))
#y=numpy.reshape(y,newshape=(l,-1))

X=pad_sequences(X,maxlen=maxlen+1,padding='pre') # +1 to have 0 as the first input
print("X:",X, type(X), X.shape)
y=pad_sequences(y,maxlen=maxlen+1,padding='pre')
print("y:",y, type(y), y.shape)

#z=numpy.
#for i in range(l):
#  z[i]=to_categorical(y[i],num_classes=vocab_size)  

#print("X=", X, "y=",y)
y=to_categorical(y,num_classes=vocab_size)

print("X=", X, "y=",y, type(X), type(y), X.shape, y.shape)
model=Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=10))
print(model.output_shape)
model.add(SimpleRNN(units=50, return_sequences=True))
print(model.output_shape)
model.add(Dense(units=vocab_size,activation='softmax'))
model.summary()
print("Input Shape of all Layers:",model.layers[0].input_shape,model.layers[1].input_shape,model.layers[2].input_shape)
print("Input Dim:",model.layers[0].input_dim)


Maxlen: 10
X: [[ 0  0  0  0  3  2  4  5  6  7  8]
 [ 0  0  0  0  0  9 10 11 12 13 14]
 [ 0  0  0  0  3 15 16  2 17 18 19]
 [ 0  0  0  0  0  0  2  4 20 21 22]] <class 'numpy.ndarray'> (4, 11)
y: [[[[[0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    ...
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]]

   [[0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    ...
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]]

   [[0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    ...
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]]

   ...

   [[0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    ...
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]]

   [[0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    ...
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]]

   [[0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    [0 0 0 ... 0 0 0]
    ...
    [0 0 0 ...

In [34]:
model.compile(optimizer="rmsprop", loss="categorical_crossentropy", metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=0)

ValueError: in user code:

    c:\users\milpitas\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:830 train_function  *
        return step_function(self, iterator)
    c:\users\milpitas\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:813 run_step  *
        outputs = model.train_step(data)
    c:\users\milpitas\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:771 train_step  *
        loss = self.compiled_loss(
    c:\users\milpitas\appdata\local\programs\python\python39\lib\site-packages\keras\engine\compile_utils.py:201 __call__  *
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    c:\users\milpitas\appdata\local\programs\python\python39\lib\site-packages\keras\losses.py:142 __call__  *
        losses = call_fn(y_true, y_pred)
    c:\users\milpitas\appdata\local\programs\python\python39\lib\site-packages\keras\losses.py:246 call  *
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    c:\users\milpitas\appdata\local\programs\python\python39\lib\site-packages\tensorflow\python\util\dispatch.py:206 wrapper  **
        return target(*args, **kwargs)
    c:\users\milpitas\appdata\local\programs\python\python39\lib\site-packages\keras\losses.py:1630 categorical_crossentropy
        return backend.categorical_crossentropy(
    c:\users\milpitas\appdata\local\programs\python\python39\lib\site-packages\tensorflow\python\util\dispatch.py:206 wrapper
        return target(*args, **kwargs)
    c:\users\milpitas\appdata\local\programs\python\python39\lib\site-packages\keras\backend.py:4827 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    c:\users\milpitas\appdata\local\programs\python\python39\lib\site-packages\tensorflow\python\framework\tensor_shape.py:1161 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 11, 23, 23, 23, 23) and (None, 11, 23) are incompatible


In [14]:
sample_seq_wo_seed(model, tokenizer, 10, 23)

NameError: name 'sample_seq_wo_seed' is not defined

In [16]:
def prob_of_input_sentence(model, tokenizer, sentence):
  print("Input Sentence:", sentence)
  encoded=tokenizer.texts_to_sequences([sentence])[0]
  encoded.insert(0,0)
  encoded=array(encoded)
  encoded=numpy.reshape(encoded,newshape=(1,-1))
  print("Encoded:", encoded, encoded.shape)
  prob=model.predict(encoded, verbose=0)
  print("Prob:", prob, prob.shape)
  probability=1
  print(prob.shape[1]-1)

  for i in range(prob.shape[1]-1):
      probability = probability * prob[0,i,encoded[0,i+1]]
  print("Probability of Sentence", "\"", sentence, "\"", "is:", probability)

In [18]:

print("-------------------Probability of Input Sentence------------------------------")  
prob_of_input_sentence(model, tokenizer, "Jack and Jill Went")

prob_of_input_sentence(model, tokenizer, "and Jill Went up")
prob_of_input_sentence(model, tokenizer, "went up the hill")
prob_of_input_sentence(model, tokenizer, "jack and Jill Went up the hill .")
prob_of_input_sentence(model, tokenizer, "to fetch a pail")
prob_of_input_sentence(model, tokenizer, "fetch a pail")
prob_of_input_sentence(model, tokenizer, "to fetch a pail of water")
prob_of_input_sentence(model, tokenizer, "jack fell down and")
prob_of_input_sentence(model, tokenizer, "jack fell down and broke")
prob_of_input_sentence(model, tokenizer, "fell down and broke")
prob_of_input_sentence(model, tokenizer, "jack fell down and broke his crown")
prob_of_input_sentence(model, tokenizer, "and jill came tumbling")
prob_of_input_sentence(model, tokenizer, "g after")
prob_of_input_sentence(model, tokenizer, "and jill came tumbling after .")
print("-------------------------------------------------------------------------------")


-------------------Probability of Input Sentence------------------------------
Input Sentence: Jack and Jill Went
Encoded: [[0 3 2 4 5]] (1, 5)
Prob: [[[0.0432098  0.04305676 0.04449883 0.04347473 0.0454534  0.04279947
   0.04393569 0.04505904 0.04221722 0.04362882 0.04330152 0.04351991
   0.04226489 0.04361827 0.04302508 0.04371072 0.04399268 0.04300125
   0.04371621 0.04320899 0.0443899  0.04250547 0.04241145]
  [0.04454481 0.04308286 0.041565   0.04398777 0.04409016 0.04343299
   0.0426928  0.04192496 0.04562202 0.04142058 0.04248499 0.04129959
   0.04794956 0.04414916 0.04332788 0.04443825 0.04132914 0.04406792
   0.04249666 0.04153483 0.04574006 0.04494638 0.04387166]
  [0.04366678 0.04431101 0.04339562 0.04409092 0.04322474 0.04530571
   0.04401663 0.04478841 0.04193326 0.04541389 0.04158254 0.04368937
   0.0426257  0.04291675 0.04255326 0.04312554 0.04517687 0.04105831
   0.04308015 0.04312139 0.04269376 0.04335243 0.04487704]
  [0.0415834  0.04524863 0.04606793 0.04437016 0.045

In [9]:
prob_of_input_sentence(model, tokenizer, "and jill came walkings after .")

Input Sentence: and jill came walkings after .
Encoded: [[ 0  2  4 20 22  1]] (1, 6)
Prob: [[[4.9114701e-01 2.3031628e-03 2.3237441e-03 4.5992678e-01 9.8911533e-04
   3.4946197e-04 1.3740661e-03 7.3432468e-04 1.1828743e-03 1.8040610e-02
   3.0402243e-04 2.0336548e-03 1.4034252e-03 2.1081141e-03 9.6242689e-04
   4.8297408e-04 1.6874889e-03 3.5596557e-03 1.8635998e-03 1.8723055e-03
   6.3066685e-04 2.8731937e-03 1.8473159e-03]
  [4.8568223e-02 6.2731182e-04 3.9620793e-01 3.0029237e-03 3.0661558e-03
   1.6486511e-04 7.4187170e-05 2.8277276e-04 1.2833611e-04 2.4541169e-01
   1.0393654e-02 1.3776933e-05 1.3746413e-03 7.8471011e-04 1.0303539e-03
   2.8268623e-01 1.6761041e-04 1.3672321e-03 1.3005611e-03 4.5544532e-04
   8.5494758e-05 1.1909134e-03 1.6149195e-03]
  [1.1228723e-04 4.3483314e-04 1.6067144e-02 5.4460354e-05 6.4136094e-01
   6.4573804e-04 1.2536463e-04 3.2795002e-04 1.4159838e-03 7.6218572e-04
   1.4984544e-01 1.8983134e-03 1.5497475e-05 1.6502462e-03 1.4782522e-03
   1.5685376e-