In [1]:
import sklearn
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
import pandas as pd
import numpy as np
x, y = datasets.load_iris(return_X_y=True)
xtrain, xtest, ytrain, ytest = sklearn.model_selection.train_test_split(x, y, test_size=0.2)
model = GaussianNB()
model.fit(xtrain, ytrain)




AttributeError: module 'sklearn' has no attribute 'model_selection'

In [4]:
predict = model.predict(xtest)
print("Classification Report\n", metrics.classification_report(ytest, predict))
print("Accuracy:",metrics.accuracy_score(ytest, predict))
print("Confusion Matrix:\n",metrics.confusion_matrix(ytest, predict))


NameError: name 'model' is not defined

In [7]:
# decision tree using ID3 and gini index
import sklearn as sk
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn import datasets
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets

x, y = datasets.load_iris(return_X_y=True)
x_train, x_test, y_train, y_test = sk.model_selection.train_test_split(x, y, test_size=0.2)
model = DecisionTreeClassifier(criterion='gini', splitter="best")
model.fit(x_train, y_train)
predict = model.predict(x_test)
print("Classification Report\n", metrics.classification_report(y_test, predict))
print("Accuracy:",metrics.accuracy_score(y_test, predict))
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, predict))

Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.85      0.92      0.88        12
           2       0.90      0.82      0.86        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.91        30
weighted avg       0.90      0.90      0.90        30

Accuracy: 0.9
Confusion Matrix:
 [[ 7  0  0]
 [ 0 11  1]
 [ 0  2  9]]


In [8]:
model1=DecisionTreeClassifier(criterion='entropy', splitter="best")
model1.fit(x_train, y_train)
predict = model.predict(x_test)
print("Classification Report\n", metrics.classification_report(y_test, predict))
print("Accuracy:",metrics.accuracy_score(y_test, predict))
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, predict))

Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.85      0.92      0.88        12
           2       0.90      0.82      0.86        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.91        30
weighted avg       0.90      0.90      0.90        30

Accuracy: 0.9
Confusion Matrix:
 [[ 7  0  0]
 [ 0 11  1]
 [ 0  2  9]]
