In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn import datasets, metrics
x,y = datasets.load_boston(return_X_y=True)
x.shape

c:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the

(506, 13)

In [9]:
train_temp1=x[0:400,:]
X_train=np.ones((train_temp1.shape[0],train_temp1.shape[1]+1))
X_train

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [7]:
#set 1st column of X_train to 1
X_train[:,0:]=1
X_train.shape
X_train

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [10]:
X_train[:,1:]=train_temp1
X_train

array([[1.00000e+00, 6.32000e-03, 1.80000e+01, ..., 1.53000e+01,
        3.96900e+02, 4.98000e+00],
       [1.00000e+00, 2.73100e-02, 0.00000e+00, ..., 1.78000e+01,
        3.96900e+02, 9.14000e+00],
       [1.00000e+00, 2.72900e-02, 0.00000e+00, ..., 1.78000e+01,
        3.92830e+02, 4.03000e+00],
       ...,
       [1.00000e+00, 7.67202e+00, 0.00000e+00, ..., 2.02000e+01,
        3.93100e+02, 1.99200e+01],
       [1.00000e+00, 3.83518e+01, 0.00000e+00, ..., 2.02000e+01,
        3.96900e+02, 3.05900e+01],
       [1.00000e+00, 9.91655e+00, 0.00000e+00, ..., 2.02000e+01,
        3.38160e+02, 2.99700e+01]])

In [11]:
y_train=y[0:400]
y_train.shape
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_train


array([[ 0.        , -0.29171468,  0.14290806, ..., -1.21945879,
         0.41941166, -0.92732759],
       [ 0.        , -0.28820481, -0.56670438, ..., -0.09220903,
         0.41941166, -0.3121236 ],
       [ 0.        , -0.28820816, -0.56670438, ..., -0.09220903,
         0.3192679 , -1.06781889],
       ...,
       [ 0.        ,  0.99011231, -0.56670438, ...,  0.98995074,
         0.32591134,  1.2820829 ],
       [ 0.        ,  6.12025956, -0.56670438, ...,  0.98995074,
         0.41941166,  2.86002199],
       [ 0.        ,  1.36543343, -0.56670438, ...,  0.98995074,
        -1.02590637,  2.76833293]])

In [6]:
alpha = 0.001
# genrate x_train.shape[0] random values for theta

theta=np.random()
iterations = 10
m=X_train.shape[0]
n=X_train.shape[1]
for i in range(iterations):
    update=np.zeroes(X_train.shape[1])
    y_pred = np.dot(X_train, theta)
    error = y_pred-y_train
    
    

SyntaxError: invalid syntax (2971717734.py, line 1)

In [16]:
import pandas as pd
df1 = pd.read_csv('bstart.csv')

In [17]:
df1

Booking Start Date  10493010
0               8192022  191019.0
1               8262022  184763.0
2               8122022  182433.0
3               8052022  176029.0
4               9022022  167985.0
..                  ...       ...
787             1122025       1.0
788             1112025       1.0
789             1112024       1.0
790             1082024       1.0
791             1052024       1.0

[792 rows x 2 columns]

In [15]:
df1.to_csv('bstart.csv')

In [2]:
# naive bayes using iris dataset
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
iris = datasets.load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
gnb = GaussianNB()
gnb.fit(X_train, y_train)


GaussianNB()

In [3]:
y_pred = gnb.predict(X_test)
print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0],(y_test != y_pred).sum()))
print("Accuracy : ",accuracy_score(y_test, y_pred))
    

Number of mislabeled points out of a total 45 points : 3
Accuracy :  0.9333333333333333


In [ ]:
sms= pd.read_table(filepath_or_buffer='',header=None,encoding='utf-8')